CREATE DATABASE IF NOT EXISTS BD_EST_SUPER;
USE BD_EST_SUPER;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TIPO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_BARRA VARCHAR(20) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    PRECO DOUBLE NOT NULL,
    FK_ID_CATEGORIA VARCHAR(100),
    FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA(ID)
);

CREATE TABLE IF NOT EXISTS FORNECEDOR_PRODUTO(
	ID INT AUTO_INCREMENT NOT NULL,
    FK_CNPJ_FORN VARCHAR(14),
    FK_CODIGO_PRODUTO VARCHAR(20),
	FOREIGN KEY (FK_CNPJ_FORN) REFERENCES FORNECEDOR(CNPJ),
	FOREIGN KEY (FK_CODIGO_PRODUTO) REFERENCES PRODUTOS(CODIGO)
);