CREATE DATABASE IF NOT EXISTS BD_APP_MUSICAS;
USE BD_APP_MUSICAS;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INT PRIMARY KEY,
    ESTILO_MUSICAL TIMESTAMP,
    RITMO VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INT PRIMARY KEY,
    MUSICAS VARCHAR(50),
    QTD_MUSICAS VARCHAR(100),
    FK_CPF_ARTISTA VARCHAR(11),
    FOREIGN KEY (FK_CPF_ARTISTA) REFERENCES ARTISTA(CPF)
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INT PRIMARY KEY,
    LETRA VARCHAR(100) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    FK_ID_ALBUM INT,
    FK_ID_GENE INT,
    FOREIGN KEY (FK_ID_ALBUM) REFERENCES ALBUM(ID),
    FOREIGN KEY (FK_ID_GENE) REFERENCES GENERO(ID)
);